---
name: Primeros Programas
locale: es
type: learning
beta: false
teacher_info: "* Objetivo: divertirse. \n* Juego: Gobstones, Programar en gobstones\n*
  Casillero: Celda\n* Reglas:\n  - Siempre posicionado en un casillero\n  - podemos
  movernos\n  - tenemos que decirle a mukinita qué hacer, en un lenguaje llamado Gobstones\n*
  Luz amarilla: cabezal\n* Mukinita: Motor de Gobstones, Runtime\n* Casillero iluminado:
  Casillero Actual / Donde estamos parados\n* Tablero final: Tablero esperado\n"
language: gobstones
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
